export const AUTH_REQUEST = "AUTH_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const AUTH_FAILIURE = "AUTH_FAILIURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
